(source gnu)

;; load from melpa-stable -----

(source melpa-stable)
(depends-on "bind-key")
(depends-on "cask")
(depends-on "emmet-mode")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "git-timemachine")
(depends-on "golden-ratio")
(depends-on "helm")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "multiple-cursors")
(depends-on "paredit")
(depends-on "smart-mode-line")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "whitespace")
(depends-on "writeroom-mode")
(depends-on "yaml-mode")
(depends-on "rainbow-delimiters")